spring:
  datasource:
    url: jdbc:h2:mem:delivery
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true 